### ISSUE TITLE
UVM testbench files with similar file name (case differences)

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/ofs-n6001#10] opened 2024-01-23 14:46 UTC
UVM testbench files with similar file name (case differences)

ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_agilex_pg.sv
ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_Agilex_PG.sv

ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_Agilex_PG_cov.sv
ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_agilex_pg_cov.sv

**Comment by sanjgan** [comment] 2024-02-08 17:14
Hi,  

It looks like one set of files is redundant. We will work on removing that.

ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_agilex_pg.sv
ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_agilex_pg_cov.sv

**Comment by sanjgan** [comment] 2024-03-13 11:15
The issue is fixed in 2024.1. The files ral_ac_src_port_gasket_agilex_pg.sv and ral_ac_src_port_gasket_agilex_pg_cov.sv are the updated and correct versions. The files ral_ac_src_port_gasket_Agilex_PG.sv and ral_ac_src_port_gasket_Agilex_PG_cov.sv are removed as part of this fix.
Closing this issue.

**Comment by sonithajmal** [comment] 2024-03-15 21:42
below are the correct one.

ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_agilex_pg.sv
ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_agilex_pg_cov.sv

Removed below redundant files from 24.1 and main.

ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_Agilex_PG.sv
ofs-2023.3/verification/testbench/ral/ral_ac_src_port_gasket_Agilex_PG_cov.sv

**Closed as completed** 2024-03-15 22:05 UTC
